set rtp+=~/.vim/bundle/Vundle.vim
call  vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'Valloric/YouCompleteMe'
Plugin 'rhysd/vim-clang-format'
Plugin 'kana/vim-operator-user'
Plugin 'scrooloose/syntastic'

" you complete me settings
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_key_list_select_completion = ['<Down>', '<C-N>']
let g:ycm_confirm_extra_conf = 0
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
let g:ycm_filetype_whitelist = { 'cpp': 1, 'c': 1, 'python':1 }

" theme
let g:solarized_termcolors=256

" clang format
let g:clang_format#code_style='google'
let g:clang_format#command='clang-format'

call  vundle#end()

syntax on
set background=dark
colorscheme solarized

set nocompatible
filetype indent on
set ruler
set number
set cursorline
set wildmenu
set showmatch
set foldenable

" tabs and indentationd
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set cindent
set smartindent
set pastetoggle=<f5>

" backspace
set backspace=indent,eol,start

set ttyfast
set mouse=a
set ttymouse=xterm2

" use the system clipboard
set clipboard=unnamed

if has('persistent_undo')
  set undofile
  set undodir=$HOME/.vim/undo
endif


