# This will be invoked after oh-my-zsh settings are set. 
# Precedence is 
# oh-my-zsh < dotfiles/zsh/zshrc < ~/zshrc.local

# ALIASES
# Attaches or starts the new tmux session

alias tm='tmux new-session -A -s work'

## HISTORY
HISTFILE=${HOME}/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history
export HISTCONTROL=ignoredups:erasedups 
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
set show-all-if-ambiguous on
set completion-ignore-case on


# EXIT CODE AT RIGHT
return_code="%{$fg_bold[white]%}[%(?..%{$fg_bold[red]%}%?%{$fg_bold[white]%})]%{$reset_color%}"
RPS1='${return_code}'


# EDITOR
autoload      edit-command-line
zle -N        edit-command-line
bindkey '\ee' edit-command-line
VISUAL='vim'
EDITOR='vim'

#### OTHERS

COMPLETION_WAITING_DOTS="true"

# cd by .. or ... or ... or mv file ..../.
alias '..'='cd ..'
alias -g ...='../..'
alias -g ..4='../../..'
alias -g ..5='../../../..'

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

## Add local zsh setting if there is any
test -e ~/zshrc.local && source ~/zshrc.local

### Alias
alias h=history
alias g=grep


